// Builds a community-gallery submission from a run and opens a pre-filled
// GitHub *issue*. A bot (.github/workflows/action_process-result-submission.yml)
// reads the JSON, records the issue author as the submitter, validates it, opens
// the PR, and closes the issue. The submitter never forks, edits a file, or
// types their username — GitHub already knows who they are.

const REPO = 'serversideup/benchkit-laravel';

// Real bug reports never carry this, so the bot ignores everything else.
const MARKER = '<!-- benchkit-result-submission -->';

const trimRoute = (route) => route && {
    path: route.path,
    requests_per_second: route.requests_per_second,
    success_rate: route.success_rate,
    p50_ms: route.p50_ms,
    p95_ms: route.p95_ms,
    p99_ms: route.p99_ms,
    total_requests: route.total_requests,
};

// Allow-list, never drop-list: the stored run carries the submitter's public
// IP (in logs), their APP_URL / internal hostname (http.target,
// laravel.environment.url), and a full ini dump. None of that belongs in a
// public file, so we copy only the fields the gallery renders.
export const trimRunForSubmission = (run) => {
    const environment = run.environment ?? {};
    const server = environment.server ?? {};
    const php = environment.php ?? {};
    const laravel = environment.laravel ?? {};
    const benchmarks = run.benchmarks ?? {};

    const http = benchmarks.http
        ? {
            mode: benchmarks.http.mode,
            duration_seconds: benchmarks.http.duration_seconds,
            connections: benchmarks.http.connections,
            io_ms: benchmarks.http.io_ms,
            routes: Object.fromEntries(
                ['static', 'json', 'db_read', 'io']
                    .filter((key) => benchmarks.http.routes?.[key])
                    .map((key) => [key, trimRoute(benchmarks.http.routes[key])]),
            ),
        }
        : null;

    const phpBench = benchmarks.php?.headline ? { headline: benchmarks.php.headline } : null;

    // Hardware benchmarks live under yabs in the app doc; flatten to clean
    // gallery shapes (same mapping runDisplay uses for the app's Hardware panel).
    const geek = benchmarks.yabs?.geekbench?.[0];
    const geekbench = geek && geek.single && geek.multi
        ? {
            single: geek.single,
            multi: geek.multi,
            version: geek.version ?? run.settings?.geekbench_version ?? null,
            url: run.extras?.geekbench_url ?? geek.url ?? null,
        }
        : null;

    const disk = Array.isArray(benchmarks.yabs?.fio) && benchmarks.yabs.fio.length
        ? benchmarks.yabs.fio.map((row) => ({
            bs: row.bs,
            speed_r: row.speed_r,
            speed_w: row.speed_w,
            speed_rw: row.speed_rw,
        }))
        : null;

    const cfspeedtest = benchmarks.cfspeedtest
        ? {
            asn: benchmarks.cfspeedtest.asn ?? null,
            colo: benchmarks.cfspeedtest.colo ?? null,
            latency_ms: benchmarks.cfspeedtest.latency_ms ?? null,
            download_mbps: benchmarks.cfspeedtest.download_mbps ?? null,
            upload_mbps: benchmarks.cfspeedtest.upload_mbps ?? null,
        }
        : null;

    return {
        schema_version: run.schema_version ?? 1,
        id: run.id,
        created_at: run.created_at,
        meta: {
            label: run.meta?.label ?? 'BenchKit run',
            provider: run.meta?.provider ?? null,
            plan: run.meta?.plan ?? null,
            datacenter: run.meta?.datacenter ?? null,
            cost: run.meta?.cost ?? null,
        },
        environment: {
            server: {
                cpu_model: server.cpu_model,
                cpu_cores: server.cpu_cores,
                cpu_frequency: server.cpu_frequency,
                os: server.os,
                ram: server.ram,
            },
            php: {
                php_version: php.php_version,
                php_variation: php.php_variation,
                octane: php.octane,
                op_cache: php.op_cache,
                memory_limit: php.memory_limit,
            },
            laravel: {
                environment: {
                    laravel_version: laravel.environment?.laravel_version,
                },
                drivers: laravel.drivers ?? undefined,
            },
        },
        benchmarks: { http, php: phpBench, cfspeedtest, geekbench, disk },
    };
};

export const buildSubmissionIssueBody = (run) => [
    MARKER,
    'Submitting my BenchKit results to the community gallery. A bot files this automatically — just click **Submit new issue** below.',
    '',
    '### Results data',
    '```json',
    JSON.stringify(trimRunForSubmission(run), null, 2),
    '```',
    '',
    '_Generated by the BenchKit app. Your GitHub username is recorded automatically as the submitter._',
].join('\n');

export const buildSubmissionIssueUrl = (run) => {
    const label = run.meta?.label ?? 'BenchKit run';

    const params = new URLSearchParams({
        title: `Result: ${label}`,
        labels: 'result-submission',
        body: buildSubmissionIssueBody(run),
    });

    return `https://github.com/${REPO}/issues/new?${params.toString()}`;
};

export const openSubmissionIssue = (run) => {
    window.open(buildSubmissionIssueUrl(run), '_blank', 'noopener');
};
