<?php

namespace App\Support;

/**
 * The GitHub issue a submission arrives as.
 *
 * The round trip through an issue is deliberate: it credits the submission to
 * the submitter's GitHub account without BenchKit needing accounts, logins, or
 * a server of its own, and every result in the gallery lands through a
 * reviewable pull request. A bot
 * (.github/workflows/action_process-result-submission.yml) reads the token,
 * records the issue author as the submitter, validates, opens the PR, and
 * closes the issue.
 */
class SubmissionIssue
{
    public const REPO = 'serversideup/benchkit-laravel';

    /**
     * Real bug reports never carry this, so the bot ignores everything else.
     * It has to survive the fallback body below too, or a submission that was
     * too long to pre-fill would never be picked up.
     */
    public const MARKER = '<!-- benchkit-result-submission -->';

    /**
     * Past this, GitHub starts cutting the request URI — the failure that made
     * all of this necessary. A worst-case Full run tokenises to about 2,800
     * characters, so this should never trip; it exists so that if the document
     * ever does outgrow a URL, the submitter is told to paste rather than
     * silently filing a truncated result.
     */
    public const MAX_URL_LENGTH = 6000;

    /** Where a reader goes to find out why the results block isn't readable. */
    public const DOCS_URL = 'https://serversideup.net/open-source/benchkit/docs/community-results#why-the-results-block-is-not-readable';

    /**
     * The routes worth tabling, in the order the gallery and the app's own run
     * view use — ordered by how much a real application looks like them.
     *
     * @var array<string, string>
     */
    protected const ROUTE_LABELS = [
        'db_read' => 'DB read',
        'json' => 'JSON API',
        'static' => 'Static',
        'io' => 'I/O-bound',
    ];

    /**
     * @param  array<string, mixed>  $document
     * @return array{url: string, body: string, prefill: bool}
     */
    public static function for(array $document, string $token): array
    {
        $body = self::body($document, $token);
        $url = self::url($document, $body);

        if (strlen($url) <= self::MAX_URL_LENGTH) {
            return ['url' => $url, 'body' => $body, 'prefill' => true];
        }

        // Too long to carry: pre-fill everything except the token so the marker
        // and the summary still arrive, and let the submitter paste the token
        // from their clipboard into the empty block.
        $fallback = self::body($document, null);

        return ['url' => self::url($document, $fallback), 'body' => $fallback, 'prefill' => false];
    }

    /**
     * The issue as a maintainer reads it: the run's identity and its numbers in
     * plain markdown, with the machine-readable submission folded away
     * underneath.
     *
     * The order matters. An issue whose first screen is an opaque blob gives a
     * reviewer nothing to react to, and a submitter no way to check their own
     * work before posting. Everything above the fold here is derived from the
     * token immediately below it, so the two can't disagree — and the bot reads
     * only the token, so the prose can never change what gets published.
     *
     * @param  array<string, mixed>  $document
     */
    public static function body(array $document, ?string $token): string
    {
        $blocks = array_filter([
            self::MARKER,
            '### '.($document['meta']['label'] ?? 'BenchKit run'),
            self::routesTable($document),
            self::environmentTable($document),
            self::payloadBlock($token),
            '_Generated by the BenchKit app_',
        ]);

        return implode("\n\n", $blocks);
    }

    /**
     * Where it ran and what it's running — one fact per row.
     *
     * A run of middle dots reads as one undifferentiated string; a label
     * against its value reads as a fact. Rows for things nobody set are left
     * out entirely rather than filled with a dash, so the table's length is
     * itself a signal of how much the submitter told us.
     *
     * @param  array<string, mixed>  $document
     */
    protected static function environmentTable(array $document): ?string
    {
        $meta = $document['meta'] ?? [];
        $server = $document['environment']['server'] ?? [];
        $php = $document['environment']['php'] ?? [];
        $cost = $meta['cost'] ?? null;

        $rows = [
            'Host' => $meta['provider'] ?? null,
            'Plan' => $meta['plan'] ?? null,
            'Datacenter' => $meta['datacenter'] ?? null,
            'Cost' => is_array($cost) ? self::number((float) $cost['amount']).' '.$cost['currency'].'/mo' : null,
            'CPU' => isset($server['cpu_cores']) ? $server['cpu_cores'].' vCPU' : null,
            'RAM' => self::memory($server['ram'] ?? null),
            'OS' => $server['os'] ?? null,
            'PHP' => isset($php['php_version'])
                ? $php['php_version'].(isset($php['php_variation']) ? ' ('.$php['php_variation'].')' : '')
                : null,
            'Laravel' => $document['environment']['laravel']['environment']['laravel_version'] ?? null,
            // Only when they're on/off in the way that isn't the default — a
            // row that always says the expected thing is a row nobody reads.
            'Octane' => ($php['octane'] ?? false) ? 'Enabled' : null,
            'OPcache' => isset($php['op_cache']) && (string) $php['op_cache'] !== '1' ? 'Disabled' : null,
        ];

        return self::table('| Environment | |', '| --- | --- |', $rows);
    }

    /**
     * A two-column table, or nothing at all when every row was empty.
     *
     * @param  array<string, ?string>  $rows
     */
    protected static function table(string $header, string $alignment, array $rows): ?string
    {
        $lines = [];

        foreach (array_filter($rows) as $label => $value) {
            $lines[] = "| {$label} | {$value} |";
        }

        return $lines === [] ? null : implode("\n", [$header, $alignment, ...$lines]);
    }

    /** ServerSpecs reports megabytes ("3181.102 MB"); "3.1 GB" is what anyone comparing hosts thinks in. */
    protected static function memory(mixed $ram): ?string
    {
        if (! is_string($ram) && ! is_numeric($ram)) {
            return null;
        }

        $value = trim((string) $ram);

        // Only megabytes are converted. A value carrying any other unit came
        // from somewhere this method doesn't know about, and passing it through
        // untouched beats confidently relabelling "8 GiB" as "8 MB".
        if (! preg_match('/^([\d.]+)\s*(?:MB)?$/i', $value, $matches)) {
            return $value === '' ? null : $value;
        }

        $megabytes = (float) $matches[1];

        if ($megabytes <= 0) {
            return null;
        }

        return $megabytes >= 1024
            ? self::number($megabytes / 1024, 1).' GB'
            : self::number($megabytes, 0).' MB';
    }

    /**
     * Throughput per route, ordered as the gallery orders it — most
     * representative of real traffic first, so the number people should be
     * reading is the one they read first.
     *
     * @param  array<string, mixed>  $document
     */
    protected static function routesTable(array $document): ?string
    {
        $rows = [];

        // Cast: a run that measured no routes carries an empty stdClass here,
        // so that it encodes as `{}` rather than `[]` for the gallery.
        $routes = (array) ($document['benchmarks']['http']['routes'] ?? []);

        foreach (self::ROUTE_LABELS as $key => $label) {
            $route = $routes[$key] ?? null;

            if (! is_array($route) || ! isset($route['requests_per_second'])) {
                continue;
            }

            $rows[] = sprintf(
                '| %s | %s req/s | %s |',
                $label,
                self::number((float) $route['requests_per_second'], 1),
                isset($route['p95_ms']) ? self::number((float) $route['p95_ms']).' ms' : '—',
            );
        }

        // Right-aligned numeric columns: figures compare by eye only when their
        // digits line up.
        return $rows === [] ? null : implode("\n", ['| Route | Throughput | p95 |', '| --- | ---: | ---: |', ...$rows]);
    }

    /**
     * The submission itself, collapsed. The one sentence inside answers the
     * only question an unreadable block in a public issue raises: whether
     * something is being hidden in it.
     */
    protected static function payloadBlock(?string $token): string
    {
        return implode("\n", [
            '<details><summary>Full results (compressed JSON output)</summary>',
            '',
            'The string below is a compressed version of your JSON results that does NOT include any'
                .' private information. [Learn what is being submitted and how to read this data yourself]('.self::DOCS_URL.')',
            '',
            '```benchkit',
            $token ?? 'Paste your submission token here (it is on your clipboard).',
            '```',
            '',
            '</details>',
        ]);
    }

    /** Trailing zeros read as false precision; "542.8 req/s" beats "542.80 req/s". */
    protected static function number(float $value, int $decimals = 2): string
    {
        if ($decimals === 0) {
            return number_format($value);
        }

        // The decimal point always survives the first rtrim, so a round
        // thousands separator can't be eaten by it.
        return rtrim(rtrim(number_format($value, $decimals, '.', ','), '0'), '.');
    }

    /**
     * The issue title: what was benchmarked, how, and where.
     *
     * Built from the run's own fields rather than from meta.label, because the
     * label is editable — a renamed run would otherwise produce a title that
     * says nothing about the variation or the preset, which are the two things
     * that decide whether two results can be compared at all.
     *
     * Deliberately short. An earlier version appended the run id to make every
     * title unique, which didn't stop GitHub flagging submissions as potential
     * duplicates — that check reads the body too, and every submission body is
     * the same handful of tables. The id is already in the bot's comment, the
     * branch name, the pull request, and the stored filename, so it was buying
     * length and nothing else.
     *
     * Each part is bounded on its own so a long provider name can't push the
     * finished title past GitHub's limit.
     *
     * @param  array<string, mixed>  $document
     */
    public static function title(array $document): string
    {
        $php = $document['environment']['php'] ?? [];
        $variation = $php['php_variation'] ?? null;

        $what = $variation === null
            ? (string) ($document['meta']['label'] ?? 'BenchKit run')
            : $variation.(($php['octane'] ?? false) ? ' + octane' : '');

        $what = mb_substr($what, 0, 60);

        if (isset($document['settings_preset'])) {
            $what .= ' ('.ucfirst((string) $document['settings_preset']).')';
        }

        // Matches how the gallery labels a run with no host named, so the issue
        // and the published result agree.
        $where = mb_substr((string) ($document['meta']['provider'] ?? 'Self-Hosted'), 0, 40);

        return "Result: {$what} - {$where}";
    }

    /**
     * @param  array<string, mixed>  $document
     */
    protected static function url(array $document, string $body): string
    {
        $query = http_build_query([
            'title' => self::title($document),
            'labels' => 'result-submission',
            'body' => $body,
        ], '', '&', PHP_QUERY_RFC3986);

        return 'https://github.com/'.self::REPO.'/issues/new?'.$query;
    }
}
