###########################################################################
# 🚨 WARNING: You must set secrets in GitHub Actions in order for this
# workflow to work. Learn more on our guide:
# https://getspin.pro/docs/guide/automating-deployments-with-github-actions
###########################################################################
name: Production Deployment
on:
  push:
    branches:
      - main
permissions:
  contents: read
  packages: write
jobs:
  build:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      docker-tags: "ghcr.io/${{ github.repository }}:${{ github.sha }}"
      dockerfile: "./Dockerfile.php"
      environment: production
    secrets: inherit
